#!/usr/bin/env python3
"""Capture and analyze a bounded, deterministic exploration of a ROM corpus."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


def movie_events(frame_count: int) -> list[tuple[int, str]]:
    """Return a conservative exploration pattern scaled to the run length."""

    if frame_count < 1:
        raise ValueError("frame count must be positive")
    boot_wait = min(frame_count, max(30, min(180, frame_count // 4)))
    if boot_wait >= frame_count - 5:
        return [(0, "none")]
    active_frames = frame_count - boot_wait
    raw = [
        (0, "none"),
        (boot_wait, "start"),
        (boot_wait + 5, "none"),
        (boot_wait + active_frames // 5, "a"),
        (boot_wait + active_frames // 5 + 5, "none"),
        (boot_wait + active_frames * 2 // 5, "right"),
        (boot_wait + active_frames * 3 // 5, "none"),
        (boot_wait + active_frames * 3 // 5 + 1, "left"),
        (boot_wait + active_frames * 4 // 5, "none"),
        (boot_wait + active_frames * 9 // 10, "up"),
        (boot_wait + active_frames * 19 // 20, "down"),
        (boot_wait + active_frames * 23 // 24, "b"),
        (frame_count, "none"),
    ]
    events: list[tuple[int, str]] = []
    for frame, buttons in raw:
        if events and frame <= events[-1][0]:
            continue
        events.append((frame, buttons))
    return events


def write_movie(path: Path, frame_count: int) -> None:
    lines = [
        "GBB_INPUT_MOVIE 1",
        "# Generated by run_voxel_corpus.py; frame held-buttons",
    ]
    lines.extend(f"{frame} {buttons}" for frame, buttons in movie_events(frame_count))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def safe_stem(entry: dict[str, Any]) -> str:
    title = re.sub(r"[^A-Za-z0-9._-]+", "_", entry.get("title", "rom"))
    title = title.strip("._-") or "rom"
    return f"{title[:64]}-{entry['sha256'][:12]}"


def run_command(command: list[str], log_path: Path, timeout: int) -> int:
    try:
        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired as error:
        output = error.stdout or ""
        log_path.write_text(output + "\nTimed out.\n", encoding="utf-8")
        return 124
    log_path.write_text(result.stdout, encoding="utf-8")
    return result.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--corpus", type=Path, default=Path("roms/voxel-observation-corpus.json")
    )
    parser.add_argument("--rom-dir", type=Path, default=None)
    parser.add_argument("--cli", type=Path, default=Path("build-desktop/gbb_cli"))
    parser.add_argument(
        "--analyzer", type=Path, default=Path("scripts/voxel_scene_analyzer.py")
    )
    parser.add_argument(
        "--report-script", type=Path, default=Path("scripts/voxel_review_report.py")
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("roms/voxel-review")
    )
    parser.add_argument("--frames", type=int, default=900)
    parser.add_argument("--max-instructions-per-frame", type=int, default=10_000_000)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--skip-existing", action="store_true")
    args = parser.parse_args()

    if args.frames < 1 or args.timeout < 1 or args.max_instructions_per_frame < 1:
        parser.error("--frames, --timeout, and --max-instructions-per-frame must be positive")
    corpus = json.loads(args.corpus.read_text(encoding="utf-8"))
    entries = corpus.get("entries", [])
    if args.limit is not None:
        if args.limit < 1:
            parser.error("--limit must be positive")
        entries = entries[:args.limit]
    if not entries:
        parser.error("the corpus contains no entries")
    if not args.cli.is_file():
        parser.error(f"CLI executable does not exist: {args.cli}")
    if not args.analyzer.is_file():
        parser.error(f"analyzer does not exist: {args.analyzer}")
    if not args.report_script.is_file():
        parser.error(f"report script does not exist: {args.report_script}")

    rom_dir = args.rom_dir or Path(corpus.get("rom_directory", "roms"))
    observations_dir = args.output_dir / "observations"
    proposals_dir = args.output_dir / "proposals"
    movies_dir = args.output_dir / "movies"
    logs_dir = args.output_dir / "logs"
    for directory in (observations_dir, proposals_dir, movies_dir, logs_dir):
        directory.mkdir(parents=True, exist_ok=True)

    results: list[dict[str, Any]] = []
    for index, entry in enumerate(entries, 1):
        stem = safe_stem(entry)
        rom_path = rom_dir / entry["path"]
        movie_path = movies_dir / f"{stem}.movie"
        observations_path = observations_dir / f"{stem}.jsonl"
        proposals_path = proposals_dir / f"{stem}.json"
        log_path = logs_dir / f"{stem}.log"
        result: dict[str, Any] = {
            "path": entry["path"],
            "title": entry.get("title", ""),
            "sha256": entry["sha256"],
            "movie": movie_path.relative_to(args.output_dir).as_posix(),
            "observations": observations_path.relative_to(args.output_dir).as_posix(),
            "proposals": proposals_path.relative_to(args.output_dir).as_posix(),
            "log": log_path.relative_to(args.output_dir).as_posix(),
        }
        if not rom_path.is_file():
            result.update({"status": "missing_rom", "returncode": None})
            results.append(result)
            print(f"[{index}/{len(entries)}] missing {rom_path}")
            continue
        if args.skip_existing and observations_path.is_file() and proposals_path.is_file():
            result.update({"status": "skipped", "returncode": 0})
            results.append(result)
            print(f"[{index}/{len(entries)}] skipped {entry['path']}")
            continue

        write_movie(movie_path, args.frames)
        cli_command = [
            str(args.cli), str(rom_path), "--input-movie", str(movie_path),
            "--scene-jsonl", str(observations_path), "--frames", str(args.frames),
            "--max-instructions-per-frame", str(args.max_instructions_per_frame),
        ]
        capture_returncode = run_command(cli_command, log_path, args.timeout)
        has_partial_observations = observations_path.is_file() and observations_path.stat().st_size > 0
        if capture_returncode != 0 and not has_partial_observations:
            result.update({"status": "capture_failed", "returncode": capture_returncode})
            results.append(result)
            print(f"[{index}/{len(entries)}] capture failed {entry['path']}")
            continue

        analyzer_command = [
            sys.executable, str(args.analyzer), str(observations_path),
            "--output", str(proposals_path),
        ]
        returncode = run_command(analyzer_command, log_path, args.timeout)
        result.update({
            "status": (
                "complete" if capture_returncode == 0 and returncode == 0
                else "partial_capture" if capture_returncode != 0 and returncode == 0
                else "analysis_failed"
            ),
            "returncode": returncode if returncode != 0 else capture_returncode,
            "capture_returncode": capture_returncode,
        })
        if returncode == 0:
            try:
                proposals = json.loads(proposals_path.read_text(encoding="utf-8"))
                result["frames_analyzed"] = proposals.get("frames_analyzed", 0)
                result["proposal_count"] = len(proposals.get("proposals", []))
                result["max_confidence"] = max(
                    (float(item.get("confidence", 0.0))
                     for item in proposals.get("proposals", [])),
                    default=0.0,
                )
            except (OSError, json.JSONDecodeError):
                result["status"] = "analysis_output_invalid"
        results.append(result)
        print(f"[{index}/{len(entries)}] {result['status']} {entry['path']}")

    summary = {
        "schema": "gbb.voxel.review-run.v1",
        "corpus": args.corpus.as_posix(),
        "frames_requested": args.frames,
        "results": results,
    }
    summary_path = args.output_dir / "run-manifest.json"
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_path = args.output_dir / "index.html"
    report_command = [
        sys.executable, str(args.report_script), str(summary_path),
        "--output", str(report_path),
    ]
    report_returncode = run_command(
        report_command, logs_dir / "report.log", args.timeout
    )
    complete = sum(result["status"] == "complete" for result in results)
    partial = sum(result["status"] == "partial_capture" for result in results)
    print(f"Completed {complete}/{len(results)} corpus entries ({partial} partial captures)")
    print(f"Run manifest: {summary_path}")
    print(f"Review report: {report_path}")
    hard_failures = sum(
        result["status"] in {"capture_failed", "analysis_failed", "analysis_output_invalid"}
        for result in results
    )
    return 0 if hard_failures == 0 and report_returncode == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
