#!/usr/bin/env python3
"""Capture and analyze a bounded, deterministic exploration of a ROM corpus."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


MOVIE_VARIANT_NAMES = ("baseline", "menu", "play")


def _append_event(
    events: list[tuple[int, str]], frame: int, buttons: str,
) -> None:
    if frame < 0:
        return
    if events and frame <= events[-1][0]:
        return
    events.append((frame, buttons))


def _append_tap(
    events: list[tuple[int, str]], frame: int, button: str, duration: int = 3,
) -> int:
    _append_event(events, frame, button)
    release_frame = frame + max(1, duration)
    _append_event(events, release_frame, "none")
    return release_frame


def _append_hold(
    events: list[tuple[int, str]], frame: int, button: str, duration: int,
) -> int:
    _append_event(events, frame, button)
    release_frame = frame + max(1, duration)
    _append_event(events, release_frame, "none")
    return release_frame


def _baseline_movie_events(frame_count: int) -> list[tuple[int, str]]:
    """Return the original conservative exploration pattern."""

    if frame_count < 1:
        raise ValueError("frame count must be positive")
    boot_wait = min(frame_count, max(30, min(180, frame_count // 4)))
    if boot_wait >= frame_count - 5:
        return [(0, "none")]
    active_frames = frame_count - boot_wait
    raw = [
        (0, "none"),
        (boot_wait, "start"),
        (boot_wait + 5, "none"),
        (boot_wait + active_frames // 5, "a"),
        (boot_wait + active_frames // 5 + 5, "none"),
        (boot_wait + active_frames * 2 // 5, "right"),
        (boot_wait + active_frames * 3 // 5, "none"),
        (boot_wait + active_frames * 3 // 5 + 1, "left"),
        (boot_wait + active_frames * 4 // 5, "none"),
        (boot_wait + active_frames * 9 // 10, "up"),
        (boot_wait + active_frames * 19 // 20, "down"),
        (boot_wait + active_frames * 23 // 24, "b"),
        (frame_count, "none"),
    ]
    events: list[tuple[int, str]] = []
    for frame, buttons in raw:
        if events and frame <= events[-1][0]:
            continue
        events.append((frame, buttons))
    return events


def _menu_movie_events(frame_count: int) -> list[tuple[int, str]]:
    """Repeatedly exercise common title/menu confirmation paths."""

    boot_wait = min(frame_count, max(45, min(240, frame_count // 5)))
    events: list[tuple[int, str]] = [(0, "none")]
    cursor = boot_wait
    for button in ("start", "a", "start", "a", "b", "a"):
        cursor = _append_tap(events, cursor, button)
        cursor += 24

    # Menus commonly need a direction before accepting a selection. Keep the
    # sweep short so it remains useful for games that are already in play.
    for button in ("down", "a", "right", "a", "up", "a", "left", "a"):
        cursor = _append_tap(events, cursor, button)
        cursor += 28
    return [(frame, buttons) for frame, buttons in events if frame < frame_count]


def _play_movie_events(frame_count: int) -> list[tuple[int, str]]:
    """Advance through common menus, then keep the game state moving."""

    boot_wait = min(frame_count, max(45, min(210, frame_count // 5)))
    events: list[tuple[int, str]] = [(0, "none")]
    cursor = boot_wait
    for button in ("start", "a", "start", "a"):
        cursor = _append_tap(events, cursor, button)
        cursor += 24

    directions = ("right", "left", "up", "down")
    direction_index = 0
    while cursor < frame_count:
        direction = directions[direction_index % len(directions)]
        hold = min(42, max(12, frame_count - cursor - 1))
        cursor = _append_hold(events, cursor, direction, hold)
        if cursor >= frame_count:
            break
        cursor += 8
        cursor = _append_tap(events, cursor, "a")
        cursor += 14
        direction_index += 1
    return [(frame, buttons) for frame, buttons in events if frame < frame_count]


def movie_events(frame_count: int, variant: int = 0) -> list[tuple[int, str]]:
    """Return a deterministic bootstrap/exploration pattern for one variant."""

    if variant == 0:
        return _baseline_movie_events(frame_count)
    if variant == 1:
        return _menu_movie_events(frame_count)
    if variant == 2:
        return _play_movie_events(frame_count)
    raise ValueError(f"unsupported movie variant: {variant}")


def write_movie(path: Path, frame_count: int, variant: int = 0) -> None:
    lines = [
        "GBB_INPUT_MOVIE 1",
        "# Generated by run_voxel_corpus.py; frame held-buttons",
    ]
    lines.extend(
        f"{frame} {buttons}" for frame, buttons in movie_events(frame_count, variant)
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _scene_signature(record: dict[str, Any]) -> str:
    scene = record.get("scene", record)
    cells = sorted(
        (
            int(cell.get("screen_x", 0)) // 8,
            int(cell.get("screen_y", 0)) // 8,
            int(cell.get("tile_id", 0)),
            int(cell.get("attributes", 0)) & 0x78,
            str(cell.get("source", "background")),
        )
        for cell in scene.get("visible_tile_cells", [])
    )
    sprites = sorted(
        (
            int(sprite.get("screen_x", 0)) // 8,
            int(sprite.get("screen_y", 0)) // 8,
            int(sprite.get("tile", 0)),
            int(sprite.get("attributes", 0)) & 0x7F,
        )
        for sprite in scene.get("sprites", [])
        if sprite.get("visible")
    )
    encoded = json.dumps((cells, sprites), separators=(",", ":"))
    return hashlib.sha1(encoded.encode("utf-8")).hexdigest()


def _record_is_interactive(record: dict[str, Any]) -> bool:
    return str(record.get("input_buttons", "none")) not in {"", "none", "-"}


def capture_metrics(records: list[dict[str, Any]]) -> dict[str, Any]:
    """Score scene diversity and input response without game-specific rules."""

    if not records:
        return {
            "score": 0.0,
            "gameplay_start_index": 0,
            "gameplay_start_frame": None,
            "frames_retained": 0,
            "unique_scenes": 0,
            "scene_transitions": 0,
            "interactive_responses": 0,
        }

    signatures = [_scene_signature(record) for record in records]
    transitions = sum(
        left != right for left, right in zip(signatures, signatures[1:])
    )
    unique_scenes = len(set(signatures))
    interactive_responses = 0
    for index, record in enumerate(records):
        if not _record_is_interactive(record) or index == 0:
            continue
        after = min(len(records) - 1, index + 8)
        before_signature = signatures[index - 1]
        if signatures[after] != before_signature:
            interactive_responses += 1

    # Prefer captures that respond to input and continue changing afterwards,
    # while keeping the score bounded so one animated title screen cannot win
    # solely by changing every frame.
    transition_rate = transitions / max(1, len(records) - 1)
    diversity = min(1.0, unique_scenes / 24.0)
    response_rate = min(1.0, interactive_responses / 6.0)
    score = 0.45 * diversity + 0.35 * response_rate + 0.20 * min(
        1.0, transition_rate * 4.0
    )
    return {
        "score": round(score, 4),
        "gameplay_start_index": 0,
        "gameplay_start_frame": int(records[0].get("frame", 0)),
        "frames_retained": len(records),
        "unique_scenes": unique_scenes,
        "scene_transitions": transitions,
        "interactive_responses": interactive_responses,
    }


def select_gameplay_records(records: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Trim a static boot/title prefix while retaining the selected run."""

    if len(records) < 2:
        metrics = capture_metrics(records)
        return records, metrics

    signatures = [_scene_signature(record) for record in records]
    boot_end = min(len(records) - 1, max(30, len(records) // 5))
    start_index = boot_end
    for index in range(boot_end, len(records)):
        if not _record_is_interactive(records[index]):
            continue
        after = min(len(records) - 1, index + 12)
        window = signatures[index:after + 1]
        if len(set(window)) >= 3:
            start_index = max(0, index - 10)
            break

    selected = records[start_index:]
    metrics = capture_metrics(selected)
    metrics["gameplay_start_index"] = start_index
    metrics["gameplay_start_frame"] = int(
        records[start_index].get("frame", start_index)
    )
    metrics["frames_discarded"] = start_index
    return selected, metrics


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            records.append(json.loads(line))
    return records


def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.write_text(
        "".join(json.dumps(record, separators=(",", ":")) + "\n" for record in records),
        encoding="utf-8",
    )


def safe_stem(entry: dict[str, Any]) -> str:
    title = re.sub(r"[^A-Za-z0-9._-]+", "_", entry.get("title", "rom"))
    title = title.strip("._-") or "rom"
    return f"{title[:64]}-{entry['sha256'][:12]}"


def run_command(command: list[str], log_path: Path, timeout: int) -> int:
    try:
        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired as error:
        output = error.stdout or ""
        log_path.write_text(output + "\nTimed out.\n", encoding="utf-8")
        return 124
    log_path.write_text(result.stdout, encoding="utf-8")
    return result.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--corpus", type=Path, default=Path("roms/voxel-observation-corpus.json")
    )
    parser.add_argument("--rom-dir", type=Path, default=None)
    parser.add_argument("--cli", type=Path, default=Path("build-desktop/gbb_cli"))
    parser.add_argument(
        "--analyzer", type=Path, default=Path("scripts/voxel_scene_analyzer.py")
    )
    parser.add_argument(
        "--report-script", type=Path, default=Path("scripts/voxel_review_report.py")
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("roms/voxel-review")
    )
    parser.add_argument("--frames", type=int, default=900)
    parser.add_argument("--max-instructions-per-frame", type=int, default=10_000_000)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument(
        "--variants", type=int, default=len(MOVIE_VARIANT_NAMES),
        help="number of deterministic exploration variants to try (1-3)",
    )
    parser.add_argument("--skip-existing", action="store_true")
    args = parser.parse_args()

    if args.frames < 1 or args.timeout < 1 or args.max_instructions_per_frame < 1:
        parser.error("--frames, --timeout, and --max-instructions-per-frame must be positive")
    if not 1 <= args.variants <= len(MOVIE_VARIANT_NAMES):
        parser.error(f"--variants must be between 1 and {len(MOVIE_VARIANT_NAMES)}")
    corpus = json.loads(args.corpus.read_text(encoding="utf-8"))
    entries = corpus.get("entries", [])
    if args.limit is not None:
        if args.limit < 1:
            parser.error("--limit must be positive")
        entries = entries[:args.limit]
    if not entries:
        parser.error("the corpus contains no entries")
    if not args.cli.is_file():
        parser.error(f"CLI executable does not exist: {args.cli}")
    if not args.analyzer.is_file():
        parser.error(f"analyzer does not exist: {args.analyzer}")
    if not args.report_script.is_file():
        parser.error(f"report script does not exist: {args.report_script}")

    rom_dir = args.rom_dir or Path(corpus.get("rom_directory", "roms"))
    observations_dir = args.output_dir / "observations"
    proposals_dir = args.output_dir / "proposals"
    movies_dir = args.output_dir / "movies"
    logs_dir = args.output_dir / "logs"
    for directory in (observations_dir, proposals_dir, movies_dir, logs_dir):
        directory.mkdir(parents=True, exist_ok=True)

    results: list[dict[str, Any]] = []
    for index, entry in enumerate(entries, 1):
        stem = safe_stem(entry)
        rom_path = rom_dir / entry["path"]
        movie_path = movies_dir / f"{stem}.movie"
        observations_path = observations_dir / f"{stem}.jsonl"
        proposals_path = proposals_dir / f"{stem}.json"
        log_path = logs_dir / f"{stem}.log"
        result: dict[str, Any] = {
            "path": entry["path"],
            "title": entry.get("title", ""),
            "sha256": entry["sha256"],
            "movie": movie_path.relative_to(args.output_dir).as_posix(),
            "observations": observations_path.relative_to(args.output_dir).as_posix(),
            "proposals": proposals_path.relative_to(args.output_dir).as_posix(),
            "log": log_path.relative_to(args.output_dir).as_posix(),
        }
        if not rom_path.is_file():
            result.update({"status": "missing_rom", "returncode": None})
            results.append(result)
            print(f"[{index}/{len(entries)}] missing {rom_path}")
            continue
        if args.skip_existing and observations_path.is_file() and proposals_path.is_file():
            result.update({"status": "skipped", "returncode": 0})
            results.append(result)
            print(f"[{index}/{len(entries)}] skipped {entry['path']}")
            continue

        candidates: list[dict[str, Any]] = []
        with tempfile.TemporaryDirectory(
            prefix=f".{stem}-", dir=args.output_dir
        ) as candidate_dir_name:
            candidate_dir = Path(candidate_dir_name)
            for variant in range(args.variants):
                variant_name = MOVIE_VARIANT_NAMES[variant]
                variant_movie = candidate_dir / f"{variant_name}.movie"
                variant_observations = candidate_dir / f"{variant_name}.jsonl"
                variant_log = candidate_dir / f"{variant_name}.log"
                write_movie(variant_movie, args.frames, variant)
                cli_command = [
                    str(args.cli), str(rom_path), "--input-movie", str(variant_movie),
                    "--scene-jsonl", str(variant_observations), "--frames", str(args.frames),
                    "--max-instructions-per-frame", str(args.max_instructions_per_frame),
                ]
                capture_returncode = run_command(
                    cli_command, variant_log, args.timeout
                )
                if not variant_observations.is_file() or variant_observations.stat().st_size == 0:
                    continue
                try:
                    records = read_jsonl(variant_observations)
                except (OSError, json.JSONDecodeError):
                    continue
                selected_records, metrics = select_gameplay_records(records)
                candidates.append({
                    "variant": variant,
                    "variant_name": variant_name,
                    "capture_returncode": capture_returncode,
                    "records": selected_records,
                    "metrics": metrics,
                    "log": variant_log.read_text(encoding="utf-8"),
                })

            if not candidates:
                result.update({"status": "capture_failed", "returncode": 1})
                results.append(result)
                print(f"[{index}/{len(entries)}] capture failed {entry['path']}")
                continue

            selected = max(
                candidates,
                key=lambda candidate: (
                    float(candidate["metrics"].get("score", 0.0)),
                    candidate["capture_returncode"] == 0,
                    int(candidate["metrics"].get("unique_scenes", 0)),
                    int(candidate["metrics"].get("interactive_responses", 0)),
                ),
            )
            selected_records = selected["records"]
            write_movie(movie_path, args.frames, selected["variant"])
            write_jsonl(observations_path, selected_records)
            log_path.write_text(
                f"Selected exploration variant: {selected['variant_name']}\n"
                f"Tried variants: {', '.join(candidate['variant_name'] for candidate in candidates)}\n"
                f"Selection metrics: {json.dumps(selected['metrics'], sort_keys=True)}\n\n"
                + selected["log"],
                encoding="utf-8",
            )
            capture_returncode = int(selected["capture_returncode"])
            result.update({
                "selected_variant": selected["variant_name"],
                "variants_tried": [candidate["variant_name"] for candidate in candidates],
                "capture_metrics": selected["metrics"],
                "capture_returncode": capture_returncode,
            })

        if capture_returncode != 0 and not observations_path.is_file():
            result.update({"status": "capture_failed", "returncode": capture_returncode})
            results.append(result)
            print(f"[{index}/{len(entries)}] capture failed {entry['path']}")
            continue

        analyzer_command = [
            sys.executable, str(args.analyzer), str(observations_path),
            "--output", str(proposals_path),
        ]
        returncode = run_command(analyzer_command, log_path, args.timeout)
        result.update({
            "status": (
                "complete" if capture_returncode == 0 and returncode == 0
                else "partial_capture" if capture_returncode != 0 and returncode == 0
                else "analysis_failed"
            ),
            "returncode": returncode if returncode != 0 else capture_returncode,
            "capture_returncode": capture_returncode,
        })
        if returncode == 0:
            try:
                proposals = json.loads(proposals_path.read_text(encoding="utf-8"))
                result["frames_analyzed"] = proposals.get("frames_analyzed", 0)
                result["proposal_count"] = len(proposals.get("proposals", []))
                result["max_confidence"] = max(
                    (float(item.get("confidence", 0.0))
                     for item in proposals.get("proposals", [])),
                    default=0.0,
                )
            except (OSError, json.JSONDecodeError):
                result["status"] = "analysis_output_invalid"
        results.append(result)
        print(f"[{index}/{len(entries)}] {result['status']} {entry['path']}")

    summary = {
        "schema": "gbb.voxel.review-run.v2",
        "corpus": args.corpus.as_posix(),
        "frames_requested": args.frames,
        "variants_requested": args.variants,
        "variant_names": list(MOVIE_VARIANT_NAMES[:args.variants]),
        "results": results,
    }
    summary_path = args.output_dir / "run-manifest.json"
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_path = args.output_dir / "index.html"
    report_command = [
        sys.executable, str(args.report_script), str(summary_path),
        "--output", str(report_path),
    ]
    report_returncode = run_command(
        report_command, logs_dir / "report.log", args.timeout
    )
    complete = sum(result["status"] == "complete" for result in results)
    partial = sum(result["status"] == "partial_capture" for result in results)
    print(f"Completed {complete}/{len(results)} corpus entries ({partial} partial captures)")
    print(f"Run manifest: {summary_path}")
    print(f"Review report: {report_path}")
    hard_failures = sum(
        result["status"] in {"capture_failed", "analysis_failed", "analysis_output_invalid"}
        for result in results
    )
    return 0 if hard_failures == 0 and report_returncode == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
